[package]
name = "keymap"
version = "0.1.0"
authors = ["jibuntu"]

[dependencies]
libc = "0.2.43"
regex = "1.0.5"
lazy_static = "1.1.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
lazy_static = "1.1.0"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false